# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hovercraft.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hovercraft.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10hovercraft.proto\"z\n\x06Motors\x12\x11\n\tmotor_A_1\x18\x01 \x02(\r\x12\x11\n\tmotor_A_2\x18\x02 \x02(\r\x12\x11\n\tmotor_B_1\x18\x03 \x02(\r\x12\x11\n\tmotor_B_2\x18\x04 \x02(\r\x12\x11\n\tmotor_C_1\x18\x05 \x02(\r\x12\x11\n\tmotor_C_2\x18\x06 \x02(\r\"\xc5\x01\n\x0fHoverCraftState\x12\x0c\n\x04roll\x18\x01 \x02(\x02\x12\r\n\x05pitch\x18\x02 \x02(\x02\x12\x0b\n\x03yaw\x18\x03 \x02(\x02\x12\r\n\x05\x61\x63\x63_x\x18\x04 \x02(\x05\x12\r\n\x05\x61\x63\x63_y\x18\x05 \x02(\x05\x12\r\n\x05\x61\x63\x63_z\x18\x06 \x02(\x05\x12\x0e\n\x06gyro_x\x18\x07 \x02(\x05\x12\x0e\n\x06gyro_y\x18\x08 \x02(\x05\x12\x0e\n\x06gyro_z\x18\t \x02(\x05\x12\r\n\x05mag_x\x18\n \x02(\x05\x12\r\n\x05mag_y\x18\x0b \x02(\x05\x12\r\n\x05mag_z\x18\x0c \x02(\x05')
)




_MOTORS = _descriptor.Descriptor(
  name='Motors',
  full_name='Motors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_A_1', full_name='Motors.motor_A_1', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_A_2', full_name='Motors.motor_A_2', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_B_1', full_name='Motors.motor_B_1', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_B_2', full_name='Motors.motor_B_2', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_C_1', full_name='Motors.motor_C_1', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor_C_2', full_name='Motors.motor_C_2', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=142,
)


_HOVERCRAFTSTATE = _descriptor.Descriptor(
  name='HoverCraftState',
  full_name='HoverCraftState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='HoverCraftState.roll', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='HoverCraftState.pitch', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='HoverCraftState.yaw', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_x', full_name='HoverCraftState.acc_x', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_y', full_name='HoverCraftState.acc_y', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc_z', full_name='HoverCraftState.acc_z', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyro_x', full_name='HoverCraftState.gyro_x', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyro_y', full_name='HoverCraftState.gyro_y', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyro_z', full_name='HoverCraftState.gyro_z', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mag_x', full_name='HoverCraftState.mag_x', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mag_y', full_name='HoverCraftState.mag_y', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mag_z', full_name='HoverCraftState.mag_z', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=342,
)

DESCRIPTOR.message_types_by_name['Motors'] = _MOTORS
DESCRIPTOR.message_types_by_name['HoverCraftState'] = _HOVERCRAFTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Motors = _reflection.GeneratedProtocolMessageType('Motors', (_message.Message,), dict(
  DESCRIPTOR = _MOTORS,
  __module__ = 'hovercraft_pb2'
  # @@protoc_insertion_point(class_scope:Motors)
  ))
_sym_db.RegisterMessage(Motors)

HoverCraftState = _reflection.GeneratedProtocolMessageType('HoverCraftState', (_message.Message,), dict(
  DESCRIPTOR = _HOVERCRAFTSTATE,
  __module__ = 'hovercraft_pb2'
  # @@protoc_insertion_point(class_scope:HoverCraftState)
  ))
_sym_db.RegisterMessage(HoverCraftState)


# @@protoc_insertion_point(module_scope)
