/* Generated by nanopb-0.4.6-dev */

#ifndef PB_HOVERCRAFT_PB_H_INCLUDED
#define PB_HOVERCRAFT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DroneState { 
    float roll; 
    float pitch; 
    float yaw; 
    int32_t acc_x; 
    int32_t acc_y; 
    int32_t acc_z; 
    int32_t gyro_x; 
    int32_t gyro_y; 
    int32_t gyro_z; 
    int32_t mag_x; 
    int32_t mag_y; 
    int32_t mag_z; 
} DroneState;

typedef struct _Motors { 
    uint32_t motor_A_1; 
    uint32_t motor_A_2; 
    uint32_t motor_B_1; 
    uint32_t motor_B_2; 
    uint32_t motor_C_1; 
    uint32_t motor_C_2; 
} Motors;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Motors_init_default                      {0, 0, 0, 0, 0, 0}
#define DroneState_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Motors_init_zero                         {0, 0, 0, 0, 0, 0}
#define DroneState_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define DroneState_roll_tag                      1
#define DroneState_pitch_tag                     2
#define DroneState_yaw_tag                       3
#define DroneState_acc_x_tag                     4
#define DroneState_acc_y_tag                     5
#define DroneState_acc_z_tag                     6
#define DroneState_gyro_x_tag                    7
#define DroneState_gyro_y_tag                    8
#define DroneState_gyro_z_tag                    9
#define DroneState_mag_x_tag                     10
#define DroneState_mag_y_tag                     11
#define DroneState_mag_z_tag                     12
#define Motors_motor_A_1_tag                     1
#define Motors_motor_A_2_tag                     2
#define Motors_motor_B_1_tag                     3
#define Motors_motor_B_2_tag                     4
#define Motors_motor_C_1_tag                     5
#define Motors_motor_C_2_tag                     6

/* Struct field encoding specification for nanopb */
#define Motors_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   motor_A_1,         1) \
X(a, STATIC,   REQUIRED, UINT32,   motor_A_2,         2) \
X(a, STATIC,   REQUIRED, UINT32,   motor_B_1,         3) \
X(a, STATIC,   REQUIRED, UINT32,   motor_B_2,         4) \
X(a, STATIC,   REQUIRED, UINT32,   motor_C_1,         5) \
X(a, STATIC,   REQUIRED, UINT32,   motor_C_2,         6)
#define Motors_CALLBACK NULL
#define Motors_DEFAULT NULL

#define DroneState_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    roll,              1) \
X(a, STATIC,   REQUIRED, FLOAT,    pitch,             2) \
X(a, STATIC,   REQUIRED, FLOAT,    yaw,               3) \
X(a, STATIC,   REQUIRED, INT32,    acc_x,             4) \
X(a, STATIC,   REQUIRED, INT32,    acc_y,             5) \
X(a, STATIC,   REQUIRED, INT32,    acc_z,             6) \
X(a, STATIC,   REQUIRED, INT32,    gyro_x,            7) \
X(a, STATIC,   REQUIRED, INT32,    gyro_y,            8) \
X(a, STATIC,   REQUIRED, INT32,    gyro_z,            9) \
X(a, STATIC,   REQUIRED, INT32,    mag_x,            10) \
X(a, STATIC,   REQUIRED, INT32,    mag_y,            11) \
X(a, STATIC,   REQUIRED, INT32,    mag_z,            12)
#define DroneState_CALLBACK NULL
#define DroneState_DEFAULT NULL

extern const pb_msgdesc_t Motors_msg;
extern const pb_msgdesc_t DroneState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Motors_fields &Motors_msg
#define DroneState_fields &DroneState_msg

/* Maximum encoded size of messages (where known) */
#define DroneState_size                          114
#define Motors_size                              36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
